MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  KEYPOINTS_ON: True
  BODY_UV_ON: True
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  GAMMA: 0.1
  WARM_UP_ITERS: 1000
  WARM_UP_FACTOR: 0.1
  # Linear scaling rule:
  # 1 GPU:
  #BASE_LR: 0.00025
  #MAX_ITER: 720000
  #STEPS: [0, 480000, 640000]
  # 2 GPUs:
  #BASE_LR: 0.0005
  #MAX_ITER: 66600
  #STEPS: [0, 44400, 59200]
  # 2 GPUs:
  #BASE_LR: 0.0005
  #MAX_ITER: 99900
  #STEPS: [0, 66600, 88800]
  # 4 GPUs:
  #BASE_LR: 0.001
  #MAX_ITER: 33300
  #STEPS: [0, 22200, 29600]
  # 4 GPUs:
  #BASE_LR: 0.001
  #MAX_ITER: 566428
  #STEPS: [0, 377618, 503491]
  BASE_LR: 0.001
  MAX_ITER: 99900
  STEPS: [0, 66600, 88800]
  # 8 GPUs:
  # BASE_LR: 0.002
  # MAX_ITER: 130000
  # STEPS: [0, 100000, 120000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_Xconv1fc_gn_head_test    #default add_roi_2mlp_head #modified 
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7 #default 7
  ROI_XFORM_SAMPLING_RATIO: 2
KRCNN:
  ROI_KEYPOINTS_HEAD: keypoint_rcnn_heads.add_roi_pose_head_v1convX
  NUM_STACKED_CONVS: 8
  NUM_KEYPOINTS: 17
  USE_DECONV_OUTPUT: True
  CONV_INIT: MSRAFill
  CONV_HEAD_DIM: 512
  UP_SCALE: 2
  HEATMAP_SIZE: 56  # ROI_XFORM_RESOLUTION (14) * UP_SCALE (2) * USE_DECONV_OUTPUT (2)
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
  KEYPOINT_CONFIDENCE: bbox
BODY_UV_RCNN:
  ROI_HEAD: body_uv_rcnn_heads.add_roi_body_uv_head_Modification_resnet
  NUM_STACKED_CONVS: 8
  NUM_PATCHES: 24
  USE_DECONV_OUTPUT: True
  CONV_INIT: MSRAFill
  CONV_HEAD_DIM: 512
  UP_SCALE: 2
  HEATMAP_SIZE: 56
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
  ##
  # Loss weights for annotation masks.(14 Parts)
  INDEX_WEIGHTS : 2.0
  # Loss weights for surface parts. (24 Parts)  
  PART_WEIGHTS : 0.3
  # Loss weights for UV regression.
  POINT_REGRESSION_WEIGHTS : 0.1
  ##
  BODY_UV_IMS: True 
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('dense_coco_2014_valminusminival',)
  SCALES: (640, 672, 704, 736, 768, 800)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  USE_FLIPPED: True
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level	
TEST:
  DATASETS: ('dense_coco_2014_minival',)
  PROPOSAL_LIMIT: 1000
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  FORCE_JSON_DATASET_EVAL: True
  DETECTIONS_PER_IM: 20
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level 
  RPN_POST_NMS_TOP_N: 1000
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
    COORD_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
    H_FLIP: True
    SCALES: (320, 420, 520, 620, 820, 920, 1020)
    MAX_SIZE: 1866
    SCALE_H_FLIP: True
    SCALE_SIZE_DEP: False
    AREA_TH_LO: 2500   # 50^2
    AREA_TH_HI: 32400  # 180^2
    ASPECT_RATIOS: ()
    ASPECT_RATIO_H_FLIP: False
  BBOX_VOTE:
    ENABLED: True
    VOTE_TH: 0.9
OUTPUT_DIR: ''
